### ISSUE TITLE
Doesn't work for me

### ISSUE THREAD

**Issue by frame-dev** [philleonard/maven-progress-bar#6]
```
FrameDev@MacBook-Air Timer % (mvn install && mvn test && mvn package) | mvnp
Traceback (most recent call last):
  File "/usr/local/bin/mvnp", line 126, in <module>
    match()
  File "/usr/local/bin/mvnp", line 109, in match
    bar.finish()
AttributeError: 'NoneType' object has no attribute 'finish'

```
How can I solve this Problem?

**Comment by dbustamante** [comment]
This fix work for me (from line 105):

```
        if bar is None:
            bar = progressbar.ProgressBar(
                widgets=bar_format,
                widget_kwargs={'samples': 2},
                max_value=count + 1,
                redirect_stdout=True,
                custom_len=lambda o: ansi_length(o))
        bar.update(count)

    if not error:
        if bar is None:
            bar = progressbar.ProgressBar(
                widgets=bar_format,
                widget_kwargs={'samples': 2},
                max_value=1,
                redirect_stdout=True,
                custom_len=lambda o: ansi_length(o))
        bar.finish()
```
